services:
  atlas:
    build:
      context: ..
      dockerfile: setup/Dockerfile
    container_name: atlas
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../setup:/app/setup
    environment:
      - PYTHONUNBUFFERED=1
      - KEYDB_HOST=localhost

  keydb:
    build: 
      context: ..
      dockerfile: setup/keydbDockerfile
    container_name: keydb
    network_mode: host
    volumes: 
      - keydb_data:/data
    restart: unless-stopped
volumes:
  keydb_data:
