services:
  atlas:
    build:
      context: ..
      dockerfile: setup/Dockerfile
    container_name: atlas
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    volumes:
      - ../backend:/app/backend
      - ../setup:/app/setup
    environment:
      - PYTHONUNBUFFERED=1
      - KEYDB_HOST=localhost
  react:
    build:
      context: ..
      dockerfile: setup/reactDockerfile
    container_name: react_atlas
    working_dir: /app
    volumes:
      - ../frontend/atlas:/app
      - /app/node_modules
    network_mode: host
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
  keydb:
    build: 
      context: ..
      dockerfile: setup/keydbDockerfile
    container_name: keydb
    network_mode: host
    volumes: 
      - keydb_data:/data
    restart: unless-stopped

  
volumes:
  keydb_data:
